// frontend/src/routes/models/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { auth } from '$lib/stores/auth';
	import { listModels, registerModel } from '$lib/api';
	import type { Model } from '$lib/types';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import * as Card from '$lib/components/ui/card';
	import { Badge } from '$lib/components/ui/badge';
	import * as Select from '$lib/components/ui/select';
	import { Separator } from '$lib/components/ui/separator';

	let models: Model[] = $state([]);
	let token: string | null = $state(null);
	let name = $state('');
	let provider = $state('openai');
	let endpoint = $state('');
	let apiKey = $state('');
	let description = $state('');
	let success = $state('');
	let error = $state('');
	let loading = $state(false);

	auth.token.subscribe((v) => (token = v));

	const providers = ['ollama', 'openai', 'anthropic', 'custom'];

	onMount(async () => {
		await loadModels();
	});

	async function loadModels() {
		try {
			models = await listModels(token);
		} catch {
			error = 'Failed to load models';
		}
	}

	function handleProviderChange(value: string | undefined) {
		if (value) provider = value;
	}

	async function handleRegister(e: Event) {
		e.preventDefault();
		error = '';
		success = '';
		loading = true;
		try {
			const payload: Record<string, string> = { name, provider };
			if (endpoint) payload.endpoint = endpoint;
			if (apiKey) payload.api_key = apiKey;
			if (description) payload.description = description;
			await registerModel(payload as Parameters<typeof registerModel>[0], token);
			success = `Model "${name}" registered successfully`;
			name = '';
			endpoint = '';
			apiKey = '';
			description = '';
			await loadModels();
		} catch (err: unknown) {
			error = err instanceof Error ? err.message : 'Failed to register model';
		} finally {
			loading = false;
		}
	}
</script>

<div class="p-6">
	<h2 class="mb-6 text-2xl font-bold">Models</h2>

	<div class="grid gap-6 lg:grid-cols-2">
		<!-- Register form -->
		<Card.Root>
			<Card.Header>
				<Card.Title>Register Model</Card.Title>
				<Card.Description>Add a new model provider to Cortex</Card.Description>
			</Card.Header>
			<Card.Content>
				<form onsubmit={handleRegister} class="space-y-4">
					{#if error}
						<div class="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</div>
					{/if}
					{#if success}
						<div class="rounded-md bg-green-50 p-3 text-sm text-green-700">{success}</div>
					{/if}
					<div class="space-y-2">
						<Label for="name">Model Name</Label>
						<Input id="name" required bind:value={name} placeholder="e.g. gpt-4o" />
					</div>
					<div class="space-y-2">
						<Label>Provider</Label>
						<Select.Root type="single" value={provider} onValueChange={handleProviderChange}>
							<Select.Trigger>
								<span>{provider}</span>
							</Select.Trigger>
							<Select.Content>
								{#each providers as p}
									<Select.Item value={p}>{p}</Select.Item>
								{/each}
							</Select.Content>
						</Select.Root>
					</div>
					<div class="space-y-2">
						<Label for="endpoint">Endpoint URL</Label>
						<Input
							id="endpoint"
							bind:value={endpoint}
							placeholder="Optional"
						/>
					</div>
					<div class="space-y-2">
						<Label for="apiKey">API Key</Label>
						<Input id="apiKey" type="password" bind:value={apiKey} placeholder="Optional" />
					</div>
					<div class="space-y-2">
						<Label for="desc">Description</Label>
						<Input id="desc" bind:value={description} placeholder="Optional" />
					</div>
					<Button type="submit" class="w-full" disabled={loading}>
						{loading ? 'Registering…' : 'Register Model'}
					</Button>
				</form>
			</Card.Content>
		</Card.Root>

		<!-- Models list -->
		<div class="space-y-4">
			<h3 class="text-lg font-semibold">Available Models</h3>
			{#if models.length === 0}
				<p class="text-sm text-muted-foreground">No models available</p>
			{:else}
				<div class="grid gap-3">
					{#each models as model}
						<Card.Root>
							<Card.Content class="flex items-center justify-between p-4">
								<div>
									<p class="font-mono text-sm font-medium">{model.id}</p>
									{#if model.display_name && model.display_name !== model.id}
										<p class="text-xs text-muted-foreground">{model.display_name}</p>
									{/if}
								</div>
								<Badge variant="secondary">{model.owned_by}</Badge>
							</Card.Content>
						</Card.Root>
					{/each}
				</div>
			{/if}
		</div>
	</div>
</div>

// frontend/app/models/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/hooks/useAuth";
import { Sidebar } from "@/components/Sidebar";
import { listModels, registerModel } from "@/lib/api";
import { Model } from "@/lib/types";

export default function ModelsPage() {
  const { token, hydrated } = useAuth();
  const router = useRouter();
  const [models, setModels] = useState<Model[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  // Register form state
  const [name, setName] = useState("");
  const [provider, setProvider] = useState("ollama");
  const [endpoint, setEndpoint] = useState("");
  const [apiKey, setApiKey] = useState("");
  const [description, setDescription] = useState("");
  const [registering, setRegistering] = useState(false);

  useEffect(() => {
    if (hydrated && !token) router.replace("/login");
  }, [hydrated, token, router]);

  const fetchModels = useCallback(() => {
    setLoading(true);
    listModels(token)
      .then(setModels)
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [token]);

  useEffect(() => {
    if (token) fetchModels();
  }, [token, fetchModels]);

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccess(null);
    setRegistering(true);
    try {
      await registerModel(
        {
          name,
          provider,
          endpoint: endpoint || undefined,
          api_key: apiKey || undefined,
          description: description || undefined,
        },
        token
      );
      setSuccess(`Model "${name}" registered successfully.`);
      setName("");
      setEndpoint("");
      setApiKey("");
      setDescription("");
      fetchModels();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to register model");
    } finally {
      setRegistering(false);
    }
  };

  return (
    <div className="flex h-screen bg-gray-50 dark:bg-gray-900">
      <Sidebar />
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-4xl mx-auto px-6 py-8 space-y-8">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
              Models
            </h1>
            <p className="text-sm text-gray-500 mt-1">
              Manage AI model providers. Dynamically register models without
              restarting the server.
            </p>
          </div>

          {/* Register Model Form */}
          <section className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 p-6">
            <h2 className="text-lg font-semibold text-gray-800 dark:text-gray-100 mb-4">
              Register Model
            </h2>
            <form onSubmit={handleRegister} className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Model Name *
                  </label>
                  <input
                    required
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="e.g. llama3"
                    className="w-full rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 px-3 py-2 text-sm text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Provider *
                  </label>
                  <select
                    value={provider}
                    onChange={(e) => setProvider(e.target.value)}
                    className="w-full rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 px-3 py-2 text-sm text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  >
                    <option value="ollama">Ollama (local)</option>
                    <option value="openai">OpenAI (custom)</option>
                    <option value="anthropic">Anthropic (custom)</option>
                    <option value="custom">Custom endpoint</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Endpoint URL
                  </label>
                  <input
                    value={endpoint}
                    onChange={(e) => setEndpoint(e.target.value)}
                    placeholder="http://localhost:11434"
                    className="w-full rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 px-3 py-2 text-sm text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    API Key (optional)
                  </label>
                  <input
                    type="password"
                    value={apiKey}
                    onChange={(e) => setApiKey(e.target.value)}
                    placeholder="sk-…"
                    className="w-full rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 px-3 py-2 text-sm text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                </div>
                <div className="sm:col-span-2">
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Description
                  </label>
                  <input
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="Optional description"
                    className="w-full rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 px-3 py-2 text-sm text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                </div>
              </div>

              {error && (
                <div className="rounded-lg bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-700 px-3 py-2 text-sm text-red-700 dark:text-red-300">
                  {error}
                </div>
              )}
              {success && (
                <div className="rounded-lg bg-green-50 dark:bg-green-900/30 border border-green-200 dark:border-green-700 px-3 py-2 text-sm text-green-700 dark:text-green-300">
                  {success}
                </div>
              )}

              <button
                type="submit"
                disabled={registering}
                className="rounded-lg bg-indigo-600 px-5 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50 transition-colors"
              >
                {registering ? "Registering…" : "Register Model"}
              </button>
            </form>
          </section>

          {/* Model List */}
          <section>
            <h2 className="text-lg font-semibold text-gray-800 dark:text-gray-100 mb-3">
              Available Models
            </h2>
            {loading ? (
              <p className="text-sm text-gray-400">Loading…</p>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {models.map((m) => (
                  <div
                    key={m.id}
                    className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 px-4 py-3"
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-mono text-sm text-indigo-600 dark:text-indigo-400">
                        {m.id}
                      </span>
                      <span className="text-xs bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 px-2 py-0.5 rounded-full">
                        {m.owned_by}
                      </span>
                    </div>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-0.5">
                      {m.display_name}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </section>
        </div>
      </div>
    </div>
  );
}
