// frontend/src/routes/tools/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { auth } from '$lib/stores/auth';
	import { listTools, runTool } from '$lib/api';
	import type { Tool } from '$lib/types';
	import { Button } from '$lib/components/ui/button';
	import { Textarea } from '$lib/components/ui/textarea';
	import { Label } from '$lib/components/ui/label';
	import { Badge } from '$lib/components/ui/badge';
	import { ScrollArea } from '$lib/components/ui/scroll-area';
	import * as Card from '$lib/components/ui/card';

	let token: string | null = $state(null);
	auth.token.subscribe((v) => (token = v));

	let tools: Tool[] = $state([]);
	let selected: Tool | null = $state(null);
	let argsJson = $state('{}');
	let output = $state('');
	let error = $state('');
	let loading = $state(false);

	onMount(async () => {
		try {
			tools = await listTools(token);
		} catch {
			error = 'Failed to load tools';
		}
	});

	function selectTool(tool: Tool) {
		selected = tool;
		argsJson = '{}';
		output = '';
		error = '';
	}

	async function handleRun() {
		if (!selected) return;
		error = '';
		output = '';
		loading = true;
		try {
			const args = JSON.parse(argsJson);
			const res = await runTool({ tool: selected.name, args }, token);
			output = typeof res.output === 'string' ? res.output : JSON.stringify(res.output, null, 2);
		} catch (err: unknown) {
			error = err instanceof Error ? err.message : 'Failed to run tool';
		} finally {
			loading = false;
		}
	}
</script>

<div class="flex h-full">
	<!-- Tool list -->
	<div class="w-80 border-r">
		<div class="border-b p-4">
			<h2 class="text-lg font-semibold">Tools</h2>
			<p class="text-xs text-muted-foreground">{tools.length} available</p>
		</div>
		<ScrollArea class="h-[calc(100vh-8rem)]">
			<div class="space-y-1 p-2">
				{#each tools as tool}
					<button
						class="w-full rounded-lg p-3 text-left transition-colors {selected?.name === tool.name
							? 'bg-primary text-primary-foreground'
							: 'hover:bg-accent'}"
						onclick={() => selectTool(tool)}
					>
						<p class="font-mono text-sm font-medium">{tool.name}</p>
						<div class="mt-1 flex items-center gap-2">
							<Badge variant="secondary" class="text-xs">{tool.source}</Badge>
						</div>
						<p class="mt-1 line-clamp-2 text-xs opacity-75">{tool.description}</p>
					</button>
				{/each}
			</div>
		</ScrollArea>
	</div>

	<!-- Tool runner -->
	<div class="flex-1 p-6">
		{#if selected}
			<Card.Root>
				<Card.Header>
					<Card.Title class="font-mono">{selected.name}</Card.Title>
					<Card.Description>{selected.description}</Card.Description>
				</Card.Header>
				<Card.Content class="space-y-4">
					<div class="space-y-2">
						<Label for="args">Arguments (JSON)</Label>
						<Textarea id="args" rows={6} bind:value={argsJson} class="font-mono text-sm" />
					</div>
					<Button onclick={handleRun} disabled={loading}>
						{loading ? 'Running…' : 'Run Tool'}
					</Button>
					{#if error}
						<div class="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</div>
					{/if}
					{#if output}
						<div class="space-y-2">
							<Label>Output</Label>
							<pre
								class="max-h-64 overflow-auto rounded-md bg-muted p-4 font-mono text-sm">{output}</pre>
						</div>
					{/if}
				</Card.Content>
			</Card.Root>
		{:else}
			<div class="flex h-full items-center justify-center text-muted-foreground">
				<p>Select a tool from the list to run it</p>
			</div>
		{/if}
	</div>
</div>

// frontend/app/tools/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/hooks/useAuth";
import { Sidebar } from "@/components/Sidebar";
import { listTools, runTool } from "@/lib/api";
import { Tool } from "@/lib/types";

export default function ToolsPage() {
  const { token, hydrated } = useAuth();
  const router = useRouter();
  const [tools, setTools] = useState<Tool[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTool, setSelectedTool] = useState<Tool | null>(null);
  const [argsJson, setArgsJson] = useState("{}");
  const [result, setResult] = useState<string | null>(null);
  const [running, setRunning] = useState(false);
  const [runError, setRunError] = useState<string | null>(null);

  useEffect(() => {
    if (hydrated && !token) router.replace("/login");
  }, [hydrated, token, router]);

  useEffect(() => {
    if (token) {
      listTools(token)
        .then((ts) => {
          setTools(ts);
          if (ts.length > 0) setSelectedTool(ts[0]);
        })
        .catch(console.error)
        .finally(() => setLoading(false));
    }
  }, [token]);

  const handleSelectTool = (tool: Tool) => {
    setSelectedTool(tool);
    // Build default args from schema
    const props = tool.parameters?.properties as
      | Record<string, unknown>
      | undefined;
    if (props) {
      const defaults: Record<string, string> = {};
      Object.keys(props).forEach((k) => (defaults[k] = ""));
      setArgsJson(JSON.stringify(defaults, null, 2));
    } else {
      setArgsJson("{}");
    }
    setResult(null);
    setRunError(null);
  };

  const handleRun = async () => {
    if (!selectedTool) return;
    setRunError(null);
    setResult(null);
    setRunning(true);
    try {
      const args = JSON.parse(argsJson);
      const resp = await runTool({ tool: selectedTool.name, args }, token);
      setResult(JSON.stringify(resp.output, null, 2));
    } catch (e) {
      setRunError(e instanceof Error ? e.message : "Error running tool");
    } finally {
      setRunning(false);
    }
  };

  return (
    <div className="flex h-screen bg-gray-50 dark:bg-gray-900">
      <Sidebar />
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-5xl mx-auto px-6 py-8 space-y-6">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
              Tools
            </h1>
            <p className="text-sm text-gray-500 mt-1">
              Browse and run registered tools. Tools allow agents to interact
              with the world.
            </p>
          </div>

          {loading ? (
            <p className="text-sm text-gray-400">Loading tools…</p>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Tool list */}
              <div className="lg:col-span-1 space-y-2">
                {tools.map((t) => (
                  <button
                    key={t.name}
                    onClick={() => handleSelectTool(t)}
                    className={`w-full text-left rounded-xl border px-4 py-3 transition-colors ${
                      selectedTool?.name === t.name
                        ? "border-indigo-500 bg-indigo-50 dark:bg-indigo-900/30"
                        : "border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-indigo-300"
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-mono text-sm font-medium text-gray-900 dark:text-gray-100">
                        {t.name}
                      </span>
                      <span className="text-xs bg-gray-100 dark:bg-gray-700 text-gray-500 dark:text-gray-400 px-2 py-0.5 rounded-full">
                        {t.source}
                      </span>
                    </div>
                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5 line-clamp-2">
                      {t.description}
                    </p>
                  </button>
                ))}
              </div>

              {/* Tool runner */}
              {selectedTool && (
                <div className="lg:col-span-2 bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 p-6 space-y-4">
                  <div>
                    <h2 className="text-lg font-semibold text-gray-900 dark:text-white font-mono">
                      {selectedTool.name}
                    </h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-0.5">
                      {selectedTool.description}
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                      Arguments (JSON)
                    </label>
                    <textarea
                      rows={6}
                      value={argsJson}
                      onChange={(e) => setArgsJson(e.target.value)}
                      className="w-full rounded-lg border border-gray-300 dark:border-gray-600 bg-gray-50 dark:bg-gray-700 px-3 py-2 text-sm font-mono text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                  </div>

                  <button
                    onClick={handleRun}
                    disabled={running}
                    className="rounded-lg bg-indigo-600 px-5 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50 transition-colors"
                  >
                    {running ? "Running…" : "Run Tool"}
                  </button>

                  {runError && (
                    <div className="rounded-lg bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-700 px-3 py-2 text-sm text-red-700 dark:text-red-300">
                      {runError}
                    </div>
                  )}

                  {result !== null && (
                    <div>
                      <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">
                        Output
                      </p>
                      <pre className="rounded-lg bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 px-4 py-3 text-sm font-mono text-gray-900 dark:text-gray-100 overflow-auto max-h-64">
                        {result}
                      </pre>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
